name: Pipeline Lint

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      - name: Setupp node.js
        uses: actions/checkout@v2
        with:
          node-version: '20.14'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm Lint